; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; Note - For libraries
; RECOMMENDED - Accept new functionality in a backwards compatible manner and patches by pinning @ ^M.m.p

; Common - https://docs.platformio.org/en/latest/projectconf/sections/env/index.html#common-env
[env]
platform = https://github.com/pioarduino/platform-espressif32.git
framework = arduino
monitor_speed = 115200
monitor_filters = log2file, esp32_exception_decoder
lib_deps =
  etlcpp/Embedded Template Library @ ^20.44.1
; https://docs.platformio.org/en/latest/advanced/static-code-analysis/index.html
; MISRA Rules: https://github.com/speeduino/speeduino/tree/master/misra
; PVS-Studio License Comments: https://pvs-studio.com/en/blog/posts/0614/
check_tool = clangtidy, cppcheck, pvs-studio
check_flags =
  clangtidy: --checks=*
  cppcheck: --enable=all --std=c++23 --inline-suppr --platform=unspecified --addon=misra.json --addon=cert.py
  pvs-studio: --analysis-mode=0 --platform=RV32 --lic-file =
build_flags = -std=gnu++23
build_unflags = -std=gnu++11. -std=gnu++14 -std=gnu++17 -std=gnu++20

; Board Specific Environments

[env:Testing_2024-25Prod]
board = wt32-eth01
upload_speed = 921600

[env:Testing_CPWP-1]
board = esp32dev

[env:Testing_BSI-1]
board = esp32-c3-devkitm-1
