; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; Note - For libraries
; RECOMMENDED - Accept new functionality in a backwards compatible manner and patches by pinning @ ^M.m.p

[platformio]
default_envs = Prod_Nacelle

; Common - https://docs.platformio.org/en/latest/projectconf/sections/env/index.html#common-env
[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
monitor_filters = log2file, esp32_exception_decoder, colorize
; RECOMMENDED - Accept new functionality in a backwards compatible manner and patches
lib_deps =
    adafruit/Adafruit BusIO @ ^1.17.4
    ayushsharma82/ElegantOTA @ ^3.1.7
    ; br3ttb/PID @ ^1.2.1
    etlcpp/Embedded Template Library @ ^20.44.1
    lennarthennigs/ESP Telnet @ ^2.2.3
    ; madhephaestus/ESP32Servo @ ^3.1.3
    robtillaart/AS5600 @ ^0.6.7
; https://docs.platformio.org/en/latest/projectconf/sections/env/options/build/build_flags.html
; https://techoverflow.net/2021/12/14/how-to-print-all-preprocessor-flags-in-platformio/
; See also: https://interrupt.memfault.com/blog/best-and-worst-gcc-clang-compiler-flags
; Note: Not using  -Wpedantic, -Wundef, -Wconversion, -Wsign-conversion, & -Wpadded as it causes to warnings in libraries.   -Wshadow is also a bit too much. -Wstack-usage=<stack_limit> not used because it varies.
; build_flags =
;    -O3 -ffunction-sections -fdata-sections -Wl,--gc-sections
;    -std=gnu++23
;  	 -Wall -Wextra -Wdouble-promotion -Wformat=2 -Wformat-overflow=2 -Wformat-truncation=2 -fno-common -fstack-usage -Woverloaded-virtual
;    -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG
;    -E -dM -D ELEGANTOTA_USE_ASYNC_WEBSERVER=1 -D CONFIG_ASYNC_TCP_STACK_SIZE=4096
; build_flags = -O3 -ffunction-sections -fdata-sections -Wl,--gc-sections -std=gnu++23 -latomic -D ELEGANTOTA_USE_ASYNC_WEBSERVER=1 -D CONFIG_ASYNC_TCP_STACK_SIZE=4096
; build_flags =
;     -O3 -ffunction-sections -fdata-sections -Wl,--gc-sections
;     -std=gnu++23
;     -Wall -Wextra -Wdouble-promotion -Wformat=2 -Wformat-overflow=2 -Wformat-truncation=2 -fno-common -fstack-usage -Woverloaded-virtual
;     -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_VERBOSE
;     -D ELEGANTOTA_USE_ASYNC_WEBSERVER=1 -D CONFIG_ASYNC_TCP_STACK_SIZE=4096
build_flags =
    -O3 -ffunction-sections -fdata-sections -Wl,--gc-sections
    -std=gnu++23 
    -Wall -Wextra -Wdouble-promotion -Wformat=2 -Wformat-overflow=2 -Wformat-truncation=2 -fno-common -fstack-usage -Woverloaded-virtual
    -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG
    -D ELEGANTOTA_USE_ASYNC_WEBSERVER=1  -D CONFIG_ASYNC_TCP_STACK_SIZE=4096
build_unflags =
    -Os
    -std=gnu++11 -std=gnu++14 -std=gnu++17 -std=gnu++20 -std=gnu++2b -std=gnu++2a
; https://docs.platformio.org/en/latest/advanced/static-code-analysis/index.html
; MISRA Rules: https://github.com/speeduino/speeduino/tree/master/misra
; PVS-Studio License Comments: https://pvs-studio.com/en/blog/posts/0614/
check_tool = clangtidy, cppcheck
; check_tool = clangtidy, cppcheck, pvs-studio
check_flags =
    clangtidy: --checks=*
    cppcheck: --enable=all --std=c++23 --inline-suppr --platform=unspecified --addon=misra.json --addon=cert.py
    ; pvs-studio: --analysis-mode=0 --platform=RV32 --lic-file = ./PVSStudio_Lic.txt
check_skip_packages = yes
debug_tool = esp-builtin
debug_init_break = tbreak setup

; Board Specific Environments
[env:Prod_Nacelle]
; https://esp32s3.com/getting-started.html
board = dfrobot_firebeetle2_esp32c5_custom
;Compile-time "feature flag"
;-DENABLE_PITCH_ACTUATOR=0 
; Extra options already in boards file
build_flags =
    -O3 -ffunction-sections -fdata-sections -Wl,--gc-sections
    -std=gnu++23
    -Wall -Wextra -Wdouble-promotion -Wformat=2 -Wformat-overflow=2 -Wformat-truncation=2 -fno-common -fstack-usage -Woverloaded-virtual
    -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG
    -I"${platformio.packages_dir}/framework-arduinoespressif32-libs/esp32c5/include/esp_driver_tsens/include/driver"
    ; -D ARDUINO_USB_MODE=1 ; CDC/JTAG USB mode
    ; -D ARDUINO_USB_CDC_ON_BOOT=1 ; Needed for USB to enumerate when user code starts
    -D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
    ; -D CONFIG_ASYNC_TCP_MAX_ACK_TIME=5000   ; (keep default)
    ; -D CONFIG_ASYNC_TCP_PRIORITY=10         ; (keep default)
    ; -D CONFIG_ASYNC_TCP_QUEUE_SIZE=64       ; (keep default)
    ; -D CONFIG_ASYNC_TCP_RUNNING_CORE=1      ; force async_tcp task to be on same core as the app (default is core 0)
    -D CONFIG_ASYNC_TCP_STACK_SIZE=4096     ; reduce the stack size (default is 16K)

; [env:Test_2024-25Prod]
; board = wt32-eth01

; upload_speed = 921600

; [env:Test_CPWP-1]
; board = esp32dev

; [env:Test_BSI-1]
; [env:esp32-c3-devkitm-1]
; board = esp32-c3-devkitm-1
; Extra options already in boards file
; build_flags =
; 	-O3 -ffunction-sections -fdata-sections -Wl,--gc-sections
; 	-std=gnu++23
; 	-Wall -Wextra -Wdouble-promotion -Wformat=2 -Wformat-overflow=2 -Wformat-truncation=2 -fno-common -fstack-usage -Woverloaded-virtual
;   -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG
;   -I"${platformio.packages_dir}\framework-arduinoespressif32-libs\esp32\include\esp_driver_tsens\include\driver"
; 	; -D ARDUINO_USB_MODE=1 ; CDC/JTAG USB mode
; 	; -D ARDUINO_USB_CDC_ON_BOOT=1 ; Needed for USB to enumerate when user code starts
;   -D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
;   ; -D CONFIG_ASYNC_TCP_MAX_ACK_TIME=5000   ; (keep default)
;   ; -D CONFIG_ASYNC_TCP_PRIORITY=10         ; (keep default)
;   ; -D CONFIG_ASYNC_TCP_QUEUE_SIZE=64       ; (keep default)
;   ; -D CONFIG_ASYNC_TCP_RUNNING_CORE=1      ; force async_tcp task to be on same core as the app (default is core 0)
;   -D CONFIG_ASYNC_TCP_STACK_SIZE=4096     ; reduce the stack size (default is 16K)

